version: '3.8'

services:
  rs-ai:
    build: .
    container_name: rs_ai_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./rs_ai.db:/app/rs_ai.db
      - ./static/uploads:/app/static/uploads
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
