services:
  - type: web
    name: rs-ai-agent
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: "10000"
      - key: WHATSAPP_WABA_ID
        value: "27905447135785944"
      - key: WHATSAPP_PHONE_NUMBER_ID
        value: "418451426636680"
      - key: WHATSAPP_DISPLAY_PHONE_NUMBER
        value: "+8801816504097"
      - key: WHATSAPP_VERIFY_TOKEN
        value: "rs_whatsapp_token_2026"
      - key: FB_VERIFY_TOKEN
        value: "rs_secure_verify_token_2026"
      - key: META_GRAPH_VERSION
        value: "v23.0"
